### PR TITLE
Tidyr Lesson

### PR DESCRIPTION
**Pull request by Christopher-Peterson**
This is the staging ground for updating the tidyr lesson to v. 1.0.0 with the new pivot_longer() and pivot_wider() functions.

### CODE REVIEW

**Comment by Christopher-Peterson** [comment]
Mackenzie, I'd appreciate comments/feedback on this.  In particular, if you have any ideas for something that could work as Exercise 2 (a more complex pivot_longer()), I'd love to hear them. 
Thanks!

**Comment by mmjohn** [comment]
I think that Exercise 2 is plenty complex for this lesson. I find that these sort of transformations aren't as easy to digest as dplyr stuff. Might be useful to talk about what you're generally doing conceptually/visually for pivot() commands and separate(). No data, just colored info like they have on the cheatsheets for gather and spread.

Also, it might be good to explain why you're using unite() instead of mutate().

**Comment by Christopher-Peterson** [comment]
The tidyr cheatsheet hasn't been updated yet, but I can probably mock up
something equivalent.

How would you think about moving the muli-column pivot_longer() stuff to
the end? Is there anything in this part that you don't think is necessary?
I'm planning on using this next week in conjunction with a multi-function
summarize_at() next week.

I mostly put unite() in since it is the complement to separate(), bit I
agree that mutate()+paste() makes it redundant. I'll switch that.

Thanks!

**Comment by mmjohn** [comment]
Just to clarify, I don't think there's any reason why you can't use unite(). I think it's cool and it makes working with strings easy! I meant more just pointing out how it's useful in that sense.

I like the multi-column pivot_longer() where it is, because I feel like it will allow people to fully test their understanding of the function before moving on to separate().

**Pull request merged**
